name: Docker

on:
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: dark-repository-service

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: "5.0.x"

      - name: Lint dotnet
        run: dotnet tool restore && dotnet format --check --verbosity diagnostic
        
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          githubRepositoryLowerCase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=ghcr.io/${githubRepositoryLowerCase}
          TAG=$(date +%Y%m%d).${{ github.run_number }}

          echo IMAGE_ID=$IMAGE_ID
          echo TAG=$TAG
          docker pull $IMAGE_ID:latest

          docker build . --file Dockerfile --tag $IMAGE_ID:$TAG --tag $IMAGE_ID:latest --cache-from $IMAGE_ID:latest

      - name: Push image
        if: github.event_name == 'push'
        run: |
          githubRepositoryLowerCase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=ghcr.io/${githubRepositoryLowerCase}
          
          docker push --all-tags $IMAGE_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: "MarkusRodler/dark-server"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Bump version
        run: |
          TAG=$(date +%Y%m%d).${{ github.run_number }}
          echo TAG=$TAG
          sed -i -E "s/$IMAGE_NAME:[0-9]+\.[0-9]+$/$IMAGE_NAME:$TAG/" Repository/RepositoryService.yaml

      - name: Push version
        run: |
          TAG=$(date +%Y%m%d).${{ github.run_number }}
          echo TAG=$TAG
          git config user.name ${{ secrets.GIT_USER_NAME }}
          git config user.email ${{ secrets.GIT_USER_EMAIL }}
          git add .
          git commit -m "Bump Repository Service to $TAG"
          git push || echo "No changes to commit"
